name: aws login test

on:
    push:
        branches:
            - main
#
jobs:
    demo-job:
        runs-on: ubuntu-slim
        permissions:
            id-token: write
            contents: read
        env:
            REGION: us-east-1
        steps:
            - name: aws login
              uses: aws-actions/configure-aws-credentials@v6.2.3
              with:
                audience: sts.amazonaws.com
                aws-region: ${{env.REGION}}
                role-to-assume: arn:aws:iam::967848863323:role/gha-push-image
            - name: list ecr-repos
              run: |
                aws ecr describe-repositories \
                --region us-east-1 \
                --query 'repositories[*].repositoryName' \
                --output table