name: secret-scan

on:
    push:
    pull_request:
jobs:
    git-leaks:
        permissions:
            contents: read
            pull-requests: read
        runs-on: ubuntu-slim
        steps:
            - name: code checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: check leaks
              uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            